name: Deploy Spring Boot Microservice

on:
  push:
    branches:
      - main
      - develop

env:
  IMAGE_NAME: juanjohernan/imagenes:microservice-producto
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Compilar aplicación con Maven (sin pruebas)
        run: mvn clean package -DskipTests

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      - name: Listar imágenes locales
        run: docker images

      - name: Actualizar manifiesto de Kubernetes
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME|" kubernetes/deployment.yaml

      - name: Commit automático al manifiesto
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image reference to $IMAGE_NAME"
          branch: ${{ github.ref_name }}
      
